Patch rtems-rc-20000615-2-cvs.diff from Ralf Corsepius <corsepiu@faw.uni-ulm.de> to update multigen.

diff --git a/tools/build/multigen b/tools/build/multigen
--- a/tools/build/multigen
+++ b/tools/build/multigen
@@ -98,6 +98,12 @@ if test $config -eq 0 && test $custom -eq 0; then
   exit 1
 fi
 
+if test ! -r $rtems_srcdir/VERSION; then
+  echo "Can't find rtems"
+  echo "Check value passed to --rtems=<DIR>"
+  exit 1
+fi
+
 if test x$target != x ;then
 target_prefix=$target-
 fi
