Patch rtemsdoc-4.5.0-rc-12-cvs.diff from Ralf Corsepius <corsepiu@faw.uni-ulm.de> that makes the following changes:
  * Don't use a temporary file for ch19.texi anymore
  * pass all files to be handled by summarize as commandline arguments
  * Remove a dangling empty first line in posix1003_1.texi (texi2html
    (!) expects \input texinfo on the first line)

diff --git a/doc/posix1003.1/summarize b/doc/posix1003.1/summarize
--- a/doc/posix1003.1/summarize
+++ b/doc/posix1003.1/summarize
@@ -182,8 +182,11 @@ summarize_chapter()
   fi
 }
 
-chapters="ch01.t ch02.t ch03.t ch04.t ch05.t ch06.t ch07.t ch08.t \
-    ch09.t ch10.t ch11.t ch12.t ch13.t ch14.t ch15.t ch16.t ch17.t ch18.t"
+if test $# -lt 1; then
+  echo "Missing arguments"
+  exit 1
+fi
+chapters="$*"
 
 # go through the chapters one at a time
 for chapter in ${chapters}
