Merged very large and much appreciated patch from Chris Johns <cjohns@plessey.com.au>.  This patch includes the ods68302 bsp, the RTEMS++ class library, and the rtems++ test.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -15,6 +15,9 @@ ac_help="$ac_help
   --with-cross-host=HOST      host (cygnus)"
 ac_help="$ac_help
 \
+  --enable-gmake-print-directory    enable GNU Make's print directory"
+ac_help="$ac_help
+\
   --disable-posix 	     	    disable posix interface"
 ac_help="$ac_help
 \
@@ -22,6 +25,9 @@ ac_help="$ac_help
 ac_help="$ac_help
 \
   --disable-rtems-inlines 	    disable RTEMS inline functions (use macros)"
+ac_help="$ac_help
+\
++   --enable-cpp                           enable C++ support, and build the rtems++ library"
 ac_help="$ac_help
 \
   --enable-gcc28		    enable use of gcc 2.8.x features"
@@ -667,6 +673,14 @@ c/src/lib/libbsp/m68k/mvme162/startup/Makefile \
 c/src/lib/libbsp/m68k/mvme162/timer/Makefile \
 c/src/lib/libbsp/m68k/mvme162/tools/Makefile \
 c/src/lib/libbsp/m68k/mvme162/wrapup/Makefile \
+c/src/lib/libbsp/m68k/ods68302/Makefile \
+c/src/lib/libbsp/m68k/ods68302/clock/Makefile \
+c/src/lib/libbsp/m68k/ods68302/console/Makefile \
+c/src/lib/libbsp/m68k/ods68302/include/Makefile \
+c/src/lib/libbsp/m68k/ods68302/start302/Makefile \
+c/src/lib/libbsp/m68k/ods68302/startup/Makefile \
+c/src/lib/libbsp/m68k/ods68302/timer/Makefile \
+c/src/lib/libbsp/m68k/ods68302/wrapup/Makefile \
 c/src/lib/libcpu/m68k/Makefile \
 c/src/lib/libcpu/m68k/m68040/Makefile \
 c/src/lib/libcpu/m68k/m68040/fpsp/Makefile \
@@ -772,6 +786,8 @@ c/src/lib/libbsp/unix/posix/wrapup/Makefile"
 
 ka9q_mk="c/src/lib/libka9q/Makefile"
 
+rtemscpp_mk="c/src/lib/librtems++/Makefile"
+
 hwapi_mk="\
 c/src/lib/libhwapi/Makefile \
 c/src/lib/libhwapi/eeprom/Makefile \
@@ -819,6 +835,7 @@ c/src/tests/libtests/cpuuse/Makefile \
 c/src/tests/libtests/malloctest/Makefile \
 c/src/tests/libtests/rtmonuse/Makefile \
 c/src/tests/libtests/stackchk/Makefile \
+c/src/tests/libtests/rtems++/Makefile \
 c/src/tests/mptests/Makefile \
 c/src/tests/mptests/mp01/Makefile \
 c/src/tests/mptests/mp01/node1/Makefile \
@@ -960,7 +977,7 @@ c/src/tests/tools/unix/Makefile \
 c/src/tests/tools/unix/posix/Makefile"
 
 echo $ac_n "checking whether ${MAKE-make} sets \${MAKE}""... $ac_c" 1>&6
-echo "configure:964: checking whether ${MAKE-make} sets \${MAKE}" >&5
+echo "configure:981: checking whether ${MAKE-make} sets \${MAKE}" >&5
 set dummy ${MAKE-make}; ac_make=`echo "$2" | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_prog_make_${ac_make}_set'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1033,7 +1050,7 @@ else { echo "configure: error: can not run $ac_config_sub" 1>&2; exit 1; }
 fi
 
 echo $ac_n "checking host system type""... $ac_c" 1>&6
-echo "configure:1037: checking host system type" >&5
+echo "configure:1054: checking host system type" >&5
 
 host_alias=$host
 case "$host_alias" in
@@ -1054,7 +1071,7 @@ host_os=`echo $host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 echo "$ac_t""$host" 1>&6
 
 echo $ac_n "checking target system type""... $ac_c" 1>&6
-echo "configure:1058: checking target system type" >&5
+echo "configure:1075: checking target system type" >&5
 
 target_alias=$target
 case "$target_alias" in
@@ -1072,7 +1089,7 @@ target_os=`echo $target | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 echo "$ac_t""$target" 1>&6
 
 echo $ac_n "checking build system type""... $ac_c" 1>&6
-echo "configure:1076: checking build system type" >&5
+echo "configure:1093: checking build system type" >&5
 
 build_alias=$build
 case "$build_alias" in
@@ -1099,6 +1116,20 @@ if test "${with_cross_host+set}" = set; then
   withval="$with_cross_host"
   \
 host=$withval
+fi
+
+
+# Check whether --enable-gmake-print-directory or --disable-gmake-print-directory was given.
+if test "${enable_gmake_print_directory+set}" = set; then
+  enableval="$enable_gmake_print_directory"
+  \
+case "${enableval}" in
+  yes) RTEMS_USE_OWN_PDIR=yes ;;
+  no) RTEMS_USE_OWN_PDIR=no ;;
+  *)  { echo "configure: error: bad value ${enableval} for gmake-print-directory option" 1>&2; exit 1; } ;;
+esac
+else
+  RTEMS_USE_OWN_PDIR=yes
 fi
 
 
@@ -1143,6 +1174,17 @@ else
   RTEMS_USE_MACROS=no
 fi
 
+
++ # Check whether --enable-cpp or --disable-cpp was given.
+if test "${enable_cpp+set}" = set; then
+  enableval="$enable_cpp"
+  \
+  yes
+fi
+ RTEMS_HAS_CPLUSPLUS=yes ;;
+  no) RTEMS_HAS_CPLUSPLUS=no ;;
+  *)  { echo "configure: error: bad value ${enableval} for enable-cpp option" 1>&2; exit 1; } ;;
+esac],RTEMS_HAS_CPLUSPLUS=no)
 
 # Check whether --enable-gcc28 or --disable-gcc28 was given.
 if test "${enable_gcc28+set}" = set; then
@@ -1204,7 +1246,7 @@ case "${target}" in
 	;;
   m68k-rtems*)
 	rtems_bsp="dmv152 efi332 efi68k gen68302 gen68360 gen68360_040 idp \
-                   mvme136 mvme147 mvme147s mvme162 mvme162lx"
+                   mvme136 mvme147 mvme147s mvme162 mvme162lx ods68302"
        	makefiles=$m68k_mk
 	;;
   mips64orion-rtems*)
@@ -1263,7 +1305,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1267: checking for $ac_word" >&5
+echo "configure:1309: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_AWK'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1292,7 +1334,7 @@ test -n "$AWK" && break
 done
 
 echo $ac_n "checking whether ln -s works""... $ac_c" 1>&6
-echo "configure:1296: checking whether ln -s works" >&5
+echo "configure:1338: checking whether ln -s works" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_LN_S'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1319,7 +1361,7 @@ RTEMS_ROOT=`cd $srcdir/c; pwd`
 PROJECT_ROOT=`pwd;`
 
 # For now always generate the KA9Q TCP/IP Makefiles
-makefiles="$makefiles $ka9q_mk"
+makefiles="$makefiles $ka9q_mk $rtemscpp_mk"
 
 # Check whether --enable-tests or --disable-tests was given.
 if test "${enable_tests+set}" = set; then
@@ -1347,6 +1389,8 @@ if test "${enable_rtemsbsp+set}" = set; then
   \
 RTEMS_BSP=$enableval
 fi
+
+
 
 
 
@@ -1584,9 +1628,11 @@ s%@RTEMS_BSP@%$RTEMS_BSP%g
 s%@RTEMS_HOST@%$RTEMS_HOST%g
 s%@RTEMS_LIBC_DIR@%$RTEMS_LIBC_DIR%g
 s%@RTEMS_ROOT@%$RTEMS_ROOT%g
+s%@RTEMS_USE_OWN_PDIR@%$RTEMS_USE_OWN_PDIR%g
 s%@RTEMS_HAS_POSIX_API@%$RTEMS_HAS_POSIX_API%g
 s%@RTEMS_HAS_KA9Q@%$RTEMS_HAS_KA9Q%g
 s%@RTEMS_USE_MACROS@%$RTEMS_USE_MACROS%g
+s%@RTEMS_HAS_CPLUSPLUS@%$RTEMS_HAS_CPLUSPLUS%g
 s%@RTEMS_USE_GCC272@%$RTEMS_USE_GCC272%g
 s%@PROJECT_ROOT@%$PROJECT_ROOT%g
 s%@program_prefix@%$program_prefix%g
