2002-05-29	Ralf Corsepius <corsepiu@faw.uni-ulm.de>
	* configure.ac: Add libnetworking.
	* wrapup/Makefile.am: Ditto.

diff --git a/c/src/exec/wrapup/Makefile.am b/c/src/exec/wrapup/Makefile.am
--- a/c/src/exec/wrapup/Makefile.am
+++ b/c/src/exec/wrapup/Makefile.am
@@ -4,7 +4,7 @@
 
 
 LIBNAME = librtemscpu
-LIB = $(ARCH)/$(LIBNAME).a
+LIB = $(PROJECT_RELEASE)/lib$(MULTISUBDIR)/$(LIBNAME)$(LIB_VARIANT).a
 
 include $(top_srcdir)/../../../automake/multilib.am
 include $(top_srcdir)/../../../automake/compile.am
@@ -31,17 +31,51 @@ LIBDOSFS_OBJS = $(wildcard ../libfs/src/dosfs/$(ARCH)/*.o)
 endif
 LIBIMFS_OBJS = $(wildcard ../libfs/src/imfs/$(ARCH)/*.o)
 
+if HAS_NETWORKING
+NETWORKING_OBJS = \
+    ../libnetworking/wrapup/$(ARCH)/libnetworking.a
+endif
+
 OBJS = $(CPU_OBJS) $(CORE_OBJS) $(RTEMS_OBJS) $(SAPI_OBJS) \
     $(POSIX_OBJS) $(ITRON_OBJS) $(LIBCSUPPORT_OBJS) \
-    $(LIBBLOCK_OBJS) $(LIBDOSFS_OBJS) $(LIBIMFS_OBJS)
+    $(LIBBLOCK_OBJS) $(LIBDOSFS_OBJS) $(LIBIMFS_OBJS) \
+    $(NETWORKING_OBJS)
 
 $(LIB): ${OBJS}
-	$(make-library)
+	rm -f $@
+	test -d $(ARCH) || mkdir $(ARCH)
+	rm -rf $(ARCH)/*
+	for f in $(OBJS); do \
+	  case $$f in \
+	  *.o | *.rel) \
+	    if test -f $(ARCH)/`basename $$f`; then \
+	      if cmp $$f $(ARCH)/`basename $$f`; then \
+		true; \
+	      else \
+		echo 1>&2 "ERROR -- `basename $$f` in multiple files"; \
+		exit 1; \
+	      fi; \
+	    else \
+	      cp $$f $(ARCH)/; \
+	      chmod a-w $(ARCH)/`basename $$f`; \
+	    fi; \
+	    ;; \
+	  *.a) \
+	    cd $(ARCH); \
+	      $(AR) xv ../$$f || exit 1; \
+	      chmod a-w * ; \
+            cd ..; \
+	    ;; \
+	  esac; \
+	done
+	$(AR) rc $@ $(ARCH)/*
+	rm -f $(ARCH)/*.o
+	$(RANLIB) $@
 
 TMPINSTALL_FILES += $(PROJECT_RELEASE)/lib$(MULTISUBDIR)/$(LIBNAME)$(LIB_VARIANT).a
 
-$(PROJECT_RELEASE)/lib$(MULTISUBDIR)/$(LIBNAME)$(LIB_VARIANT).a: $(LIB)
-	$(INSTALL_DATA) $< $@
+#$(PROJECT_RELEASE)/lib$(MULTISUBDIR)/$(LIBNAME)$(LIB_VARIANT).a: $(LIB)
+#	$(INSTALL_DATA) $< $@
 
 install-hook: $(LIB)
 	@$(mkinstalldirs) $(libdir)
